adds sequencer openAPI spec and updates readme env vars
init4tech/zenith-rs pull request #38
Opened 2024-07-26 19:33 UTC by dylanlott

2024-07-26 22:52 UTC, rswanson approved these changes

2024-07-26 22:57 UTC, prestwich requested changes
types are not correct as U256 serializes to string not number

you should invoke the json serializer and document the output

2024-08-03 16:52 UTC, prestwich commented
most of these could use additional notation that they are formatted as Ethereum `Quantity`, which is to say, a 0x-prefixed minimal hex string

2024-08-03 16:54 UTC, prestwich commented on crates/builder/sequencer.openapi.yml
> +        v:
i believe this is actually incorrect. The V value is serialized based on parity rules. This _should_ be a boolean called `yParity`, and if we want to guarantee that, we can do so in quincey

2024-08-28 15:54 UTC, prestwich approved these changes

2024-08-28 16:59 UTC, dylanlott commented
### Merge activity

* **Aug 28, 12:59 PM EDT**: @dylanlott started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/init4tech/zenith-rs/38).

2024-08-28 17:00 UTC, merged